// gogen_stdlib_coverage emits a Go program that references every exported,
// non-generic function and method of every importable standard library
// package for the given GOOS/GOARCH, so that the linker keeps their code.
//
// Usage (run with the toolchain you want to build with):
//   go run gogen_stdlib_coverage.go -goos linux -goarch amd64 > main.go
//   GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -o out main.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"sort"
	"strings"
)

// packages that cannot or should not be imported by a regular program
var skipPkgs = map[string]bool{
	"unsafe":       true,
	"builtin":      true,
	"runtime/race": true, // requires -race
	"runtime/msan": true,
	"runtime/asan": true,
	"runtime/cgo":  true, // requires cgo
	"plugin":       true, // requires cgo
	"syscall/js":   true, // wasm only
}

func skipPath(p string) bool {
	if skipPkgs[p] {
		return true
	}
	for _, part := range strings.Split(p, "/") {
		if part == "internal" || part == "vendor" || part == "testdata" {
			return true
		}
	}
	return strings.HasPrefix(p, "cmd/")
}

func stdPackages(ctx build.Context) []string {
	cmd := exec.Command("go", "list", "std")
	cmd.Env = append(os.Environ(), "GOOS="+ctx.GOOS, "GOARCH="+ctx.GOARCH, "CGO_ENABLED=0")
	out, err := cmd.Output()
	if err != nil {
		fmt.Fprintln(os.Stderr, "go list std:", err)
		os.Exit(1)
	}
	var pkgs []string
	for _, l := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if l != "" && !skipPath(l) {
			pkgs = append(pkgs, l)
		}
	}
	sort.Strings(pkgs)
	return pkgs
}

// recvInfo returns the receiver's base type name and whether it is a pointer.
// Generic receivers are reported as not usable.
func recvInfo(expr ast.Expr) (name string, ptr bool, ok bool) {
	if star, isStar := expr.(*ast.StarExpr); isStar {
		expr, ptr = star.X, true
	}
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name, ptr, true
	default: // IndexExpr / IndexListExpr => generic type
		return "", false, false
	}
}

type pkgRefs struct {
	path  string
	alias string
	refs  []string
}

func collect(ctx build.Context, path, alias string) (*pkgRefs, error) {
	bp, err := ctx.Import(path, "", 0)
	if err != nil {
		return nil, err
	}
	if bp.Name == "main" || len(bp.GoFiles) == 0 {
		return nil, fmt.Errorf("no importable Go files")
	}
	fset := token.NewFileSet()
	// collect exported, non-generic, non-interface type names
	types := map[string]bool{}
	var files []*ast.File
	for _, fn := range bp.GoFiles {
		f, err := parser.ParseFile(fset, bp.Dir+"/"+fn, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, s := range gd.Specs {
				ts := s.(*ast.TypeSpec)
				if !ts.Name.IsExported() || ts.TypeParams != nil || ts.Assign.IsValid() {
					continue
				}
				if _, isIface := ts.Type.(*ast.InterfaceType); isIface {
					continue
				}
				types[ts.Name.Name] = true
			}
		}
	}
	seen := map[string]bool{}
	pr := &pkgRefs{path: path, alias: alias}
	for _, f := range files {
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || !fd.Name.IsExported() || fd.Type.TypeParams != nil {
				continue
			}
			var ref string
			if fd.Recv == nil {
				ref = alias + "." + fd.Name.Name
			} else {
				name, ptr, ok := recvInfo(fd.Recv.List[0].Type)
				if !ok || !types[name] {
					continue
				}
				if ptr {
					ref = "(*" + alias + "." + name + ")." + fd.Name.Name
				} else {
					ref = alias + "." + name + "." + fd.Name.Name
				}
			}
			if !seen[ref] {
				seen[ref] = true
				pr.refs = append(pr.refs, ref)
			}
		}
	}
	sort.Strings(pr.refs)
	return pr, nil
}

func main() {
	goos := flag.String("goos", build.Default.GOOS, "target GOOS")
	goarch := flag.String("goarch", build.Default.GOARCH, "target GOARCH")
	flag.Parse()
	ctx := build.Default
	ctx.GOOS, ctx.GOARCH, ctx.CgoEnabled = *goos, *goarch, false
	var all []*pkgRefs
	skipped := 0
	for i, p := range stdPackages(ctx) {
		pr, err := collect(ctx, p, fmt.Sprintf("p%03d", i))
		if err != nil {
			fmt.Fprintf(os.Stderr, "skip %s: %v\n", p, err)
			skipped++
			continue
		}
		all = append(all, pr)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gogen_stdlib_coverage.go for %s/%s with %s; DO NOT EDIT.\n\n", ctx.GOOS, ctx.GOARCH, runtimeVersion())
	b.WriteString("package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n")
	for _, pr := range all {
		if len(pr.refs) == 0 {
			// nothing referencable, a blank import still links its init code
			fmt.Fprintf(&b, "\t_ %q\n", pr.path)
		} else {
			fmt.Fprintf(&b, "\t%s %q\n", pr.alias, pr.path)
		}
	}
	b.WriteString(")\n\n")
	// one var per package keeps imports used even without exported functions
	total := 0
	b.WriteString("var keep = [][]any{\n")
	for _, pr := range all {
		if len(pr.refs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t// %s\n\t{\n", pr.path)
		for _, r := range pr.refs {
			fmt.Fprintf(&b, "\t\t%s,\n", r)
		}
		b.WriteString("\t},\n")
		total += len(pr.refs)
	}
	b.WriteString("}\n\n")
	b.WriteString("func main() {\n\tif len(os.Args) == 0x7fffffff {\n\t\tfor _, k := range keep {\n\t\t\tfor _, f := range k {\n\t\t\t\tfmt.Printf(\"%p\\n\", f)\n\t\t\t}\n\t\t}\n\t}\n\tfmt.Println(len(keep))\n}\n")
	os.Stdout.Write(b.Bytes())
	fmt.Fprintf(os.Stderr, "packages: %d used, %d skipped; references: %d\n", len(all), skipped, total)
}

func runtimeVersion() string {
	out, err := exec.Command("go", "env", "GOVERSION").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}
