"""jemalloc built with MSVC, beside the MinGW builds of the same tags.

jemalloc.py explains why this was deferred: ``msvc/ReadMe.txt`` wants
``sh -c "CC=cl ./autogen.sh"`` before the solution opens, and
``include/jemalloc/`` holds only ``.h.in`` templates until autoconf and
configure have run. windows-reference-data.yml now installs autoconf from the
image's own MSYS2 ("Install autoconf"), kept off PATH and reached through
``%AUTOTOOLS_BASH%``; the reasons, and the assertion that PATH and the
environment are unchanged, are in that step's comment. On the runner PATH
already carries Git for Windows' usr\\bin, so sh, bash, perl, link, find and
sort resolve to Git's copies there too, behind Strawberry, MSVC and System32.
The MSYS2 tools are visible only inside the login shell these steps start.

Releases. 3.6.0 has no MSVC build: there is no msvc/ directory at any 3.x tag.
The four that do are all recorded - 4.5.0, 5.2.1, 5.3.0 and 5.4.0 - because
each is a different allocator below the public entry points (see jemalloc.py),
and because the source is the same tags the MinGW artefacts were built from,
so a pair differs in the compiler and nothing else.

What was read rather than assumed:

  * Each tag's msvc/ solution builds the ``jemalloc`` project to a DLL from
    the Release configuration: msvc\\<Win32|x64>\\Release\\jemalloc.dll, from
    OutDir = $(SolutionDir)$(Platform)\\$(Configuration)\\. The solution is
    jemalloc_vc2015.sln at 4.5.0, vc2017 at 5.2.1 and 5.3.0, vc2022 at 5.4.0.
    Its platform is "x86" where the project's is "Win32". The project builds
    src/*.c only, so the C++ wrapper is out, as in the MinGW recipe, and
    ``--disable-cxx`` is passed wherever configure has it (5.x, not 4.5.0).
  * Every Release project pins a toolset (v140, v141, v141, v143) and 4.5.0
    pins Windows SDK 8.1. The runner has neither, so PlatformToolset=v143 and
    WindowsTargetPlatformVersion=10.0 go on the command line, which beats the
    project's own PropertyGroup.
  * The Release projects set /O2 /Oi /Gy /W3 and turn on WholeProgramOptimization
    and both link-time folding switches, and say nothing about the runtime
    library, which MSBuild defaults to /MD. What this corpus wants is /MD
    stated, /GL /LTCG /OPT:REF /OPT:ICF off, /Brepro and /INCREMENTAL:NO.
    WholeProgramOptimization is set in a PropertyGroup evaluated before
    Microsoft.Cpp.props, so it is cleared as a command-line global as well as
    in the props file; the rest arrive through jemalloc-corpus.props, imported
    with ForceImportBeforeCppTargets. No file in the tree is edited.
    MSBuild's tracker logs are printed into the build log, and the 5.3.0 run
    shows what was actually given: cl "/O2 /Oi /D _REENTRANT /D _WINDLL /D
    DLLEXPORT /D NDEBUG /MD /GS /Gy /Zi" with no /GL, link "/INCREMENTAL:NO
    /DEBUG /OPT:NOREF /OPT:NOICF /Brepro", and dumpbin lists VCRUNTIME140.dll
    and api-ms-win-crt-*, so the CRT is imported and stays attributed to
    data/MSVC. link prints /LTCGOUT whatever it is given; it names an
    intermediate file and does not enable /LTCG.

What the runner needed, each of which was hit rather than foreseen:

  * configure has to be told what it is. autoconf under MSYS2 guesses
    x86_64-pc-msys, which configure.ac's ``*-*-mingw* | *-*-cygwin*`` case does
    not match, so it would report "Unsupported operating system" and pick
    abi=elf. ReadMe.txt's route is Cygwin, whose triple is x86_64-pc-cygwin, so
    both --build and --host say that (both, so that autoconf does not decide
    it is cross compiling and skip the tests that run a program). The log
    then reads "checking for x86_64-pc-cygwin-gcc... cl", "checking whether we
    are cross compiling... no" and "checking whether compiler is MSVC... yes".
    Pointer width with cl comes from LG_SIZEOF_PTR_WIN, not from the triple,
    so the same string serves the x86 leg.
  * configure cannot find its own version. Under MSYS2's bash 5.3 the
    ``test ! "${srcroot}" && cd "${srcroot}"`` in configure.ac is an error -
    "./configure: line 8977: cd: null directory" - so the git branch is
    skipped and the result is "Missing VERSION file, and unable to generate
    it; creating bogus VERSION", which embeds
    0.0.0-0-g000000missing_version_try_git_fetch_tags in the DLL. The version
    is given with --with-version instead, in the form
    ``git describe --long --abbrev=40`` prints on the tagged commit.
  * The 5.x Release|Win32 project lacks a define its x64 sibling has:
    "error C1083: Cannot open include file:
    'jemalloc/internal/private_namespace.h': No such file or directory" from
    jemalloc_preamble.h, on all three of 5.2.1, 5.3.0 and 5.4.0 x86 (4.5.0 has
    no such include). That header is generated by make from the built objects,
    which this build never runs. Release|x64 defines
    JEMALLOC_NO_PRIVATE_NAMESPACE, so Win32 is given the same with /D from the
    props file, conditioned on Platform. 4.5.0 and the x64 legs are untouched.
  * autoconf 2.73 is what the wrapper picks by default and every 5.x tag
    configures with it; WANT_AUTOCONF=2.71 also works and is not needed.

One thing worth knowing about the result: configure searches the inherited
Windows PATH, so its log finds xsltproc in Strawberry and ld in mingw64. Neither
is used - the build is the vcxproj, and configure only writes headers - and no
compiler other than cl is involved.
"""

from ..recipe import Artifact, BuildStep, Recipe, Source


# Fails with a sentence rather than with cmd.exe's complaint about an empty
# command, for whoever runs this recipe somewhere the workflow step has not.
_CHECK_BASH = (
    'python -c "'
    "import os,sys;"
    "p=os.environ.get('AUTOTOOLS_BASH');"
    "sys.exit(0 if p and os.path.isfile(p) else "
    "'AUTOTOOLS_BASH is not set to an MSYS2 bash; the Install autoconf step "
    "of windows-reference-data.yml sets it')"
    '"')

# One MSYS login shell per step, with the Windows PATH appended
# (MSYS2_PATH_TYPE=inherit) so that cl is found, and CHERE_INVOKING so that it
# stays in the source root instead of going to $HOME. The directory of cl.exe
# goes first inside this process only: the MSYS /usr/bin is ahead of the
# inherited Windows PATH and holds coreutils' link.exe, which cl would
# otherwise run in place of MSVC's linker.
_ENV = {"MSYS2_PATH_TYPE": "inherit", "CHERE_INVOKING": "1", "MSYSTEM": "MSYS"}
_SH = ('"%AUTOTOOLS_BASH%" -lc '
       '"PATH=$(command -v cl | sed \'s,/[^/]*$,,\'):$PATH; ')

# Cygwin's triple, which is what the documented route yields. MSYS2's
# config.guess says x86_64-pc-msys, which configure.ac's
# `*-*-mingw* | *-*-cygwin*` case does not match: it falls through to
# "Unsupported operating system" and abi=elf. Both --build and --host, so that
# autoconf does not decide it is cross compiling and skip the tests that run a
# program. Pointer width does not come from the triple with cl, only from
# LG_SIZEOF_PTR_WIN, so the same string serves the x86 leg.
_TRIPLE = "--build=x86_64-pc-cygwin --host=x86_64-pc-cygwin"


def _autogen(cxx, version, commit):
    # --with-version because configure asks git, and cannot: under MSYS2's
    # bash 5.3 its `test ! "${srcroot}" && cd "${srcroot}"` is an error
    # ("./configure: line 8977: cd: null directory") where it is a no-op
    # elsewhere, so it falls through to "Missing VERSION file, and unable to
    # generate it; creating bogus VERSION" and the DLL would say
    # 0.0.0-0-g000000missing_version_try_git_fetch_tags. This is what
    # `git describe --long --abbrev=40` prints on the tagged commit.
    return BuildStep(
        _SH + 'CC=cl sh ./autogen.sh %s%s --with-version=%s-0-g%s"'
        % ("--disable-cxx " if cxx else "", _TRIPLE, version, commit),
        env=_ENV, allow_failure=True)


# The checks that make an autogen failure readable: the tail of config.log is
# what says why, and the build log the workflow prints holds only its last
# sixty lines.
_TAIL = BuildStep(_SH + 'tail -n 25 config.log"', env=_ENV, allow_failure=True)

_CHECK_HEADERS = (
    'python -c "'
    "import os,sys;"
    "f='include/jemalloc/internal/jemalloc_internal_defs.h';"
    "sys.exit(0 if os.path.isfile(f) else "
    "'autogen.sh produced no ' + f + ' - see the config.log tail above')"
    '"')

# Written from a step, not committed: a file dropped next to the solution, the
# way libsodium_msvc.py and q3vm_msvc.py do it, and nothing upstream ships is
# edited.
def _props(private_namespace_on_win32):
    # The 5.x Release|x64 project defines JEMALLOC_NO_PRIVATE_NAMESPACE and
    # Release|Win32 does not, so jemalloc_preamble.h includes
    # jemalloc/internal/private_namespace.h on x86 only - a header make
    # generates from the built objects, which this build never runs. Giving
    # Win32 the define its x64 sibling already has is the smallest change.
    # /D rather than PreprocessorDefinitions because that would need
    # %(PreprocessorDefinitions), and cmd.exe reads a % as its own.
    extra = (
        "'<ItemDefinitionGroup Condition=\\x22$(Platform)==Win32\\x22>'"
        "'<ClCompile><AdditionalOptions>/DJEMALLOC_NO_PRIVATE_NAMESPACE'"
        "'</AdditionalOptions></ClCompile></ItemDefinitionGroup>'"
        if private_namespace_on_win32 else "")
    return (
        'python -c "'
        "open('jemalloc-corpus.props','w').write("
        "'<Project><PropertyGroup><LinkIncremental>false</LinkIncremental>'"
        "'</PropertyGroup><ItemDefinitionGroup><ClCompile>'"
        "'<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>'"
        "'<DebugInformationFormat>ProgramDatabase</DebugInformationFormat>'"
        "'<WholeProgramOptimization>false</WholeProgramOptimization>'"
        "'</ClCompile><Link>'"
        "'<GenerateDebugInformation>true</GenerateDebugInformation>'"
        "'<ProgramDatabaseFile>$(OutDir)$(TargetName).pdb</ProgramDatabaseFile>'"
        "'<EnableCOMDATFolding>false</EnableCOMDATFolding>'"
        "'<OptimizeReferences>false</OptimizeReferences>'"
        "'<LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>'"
        "'<AdditionalOptions>/Brepro</AdditionalOptions>'"
        "'</Link></ItemDefinitionGroup>'" + extra +
        "'</Project>')"
        '"')


_MSBUILD = ('msbuild msvc\\%s /t:jemalloc /p:Configuration=Release '
            '/p:Platform={arch} /p:PlatformToolset=v143 '
            '/p:WindowsTargetPlatformVersion=10.0 '
            '/p:WholeProgramOptimization=false '
            '/p:ForceImportBeforeCppTargets=%%CD%%\\jemalloc-corpus.props '
            '/m /v:minimal')

# What the compiler and linker were actually given, out of MSBuild's tracker
# logs, so that the flags claimed in build_flags are read off the build.
_TLOGS = (
    'python -c "'
    "import glob;"
    "[print(f+chr(10)+open(f,'rb').read().decode('utf-16','replace')"
    ".encode('ascii','replace').decode()) "
    "for f in sorted(glob.glob('msvc/projects/*/jemalloc/*/*/jemalloc.tlog/"
    "*.command.*.tlog'))]"
    '"')

_OUT = "msvc\\{msbuild_platform}\\Release\\"

_FLAGS = ("/O2 /Oi /Gy /W3 /Zi (upstream Release, unmodified); /MD stated "
          "explicitly; /GL turned off (upstream sets it); /DEBUG /Brepro "
          "/INCREMENTAL:NO /OPT:NOREF /OPT:NOICF at link (upstream's /OPT:REF "
          "/OPT:ICF turned off); toolset retargeted to v143")


_COMMON_NOTES = (
    "Built from upstream's own msvc/ solution, Release configuration, after "
    "autoconf has generated the headers with CC=cl; the same tag as the "
    "MinGW artefact, so the pair differs in the compiler. Built against the "
    "DLL runtime, so the MSVC C runtime is imported rather than linked in "
    "and stays attributed to data/MSVC. The C++ wrapper is not part of the "
    "project. The version string is passed to configure, because it cannot "
    "run git under the runner's shell. ")

_X86_NOTE = (
    "The x86 build defines JEMALLOC_NO_PRIVATE_NAMESPACE, which upstream's "
    "Release|x64 project defines and its Release|Win32 project does not; "
    "without it the x86 build needs a header that make generates. ")


def _jemalloc_msvc(version, commit, sln, is_5x, notes):
    notes = notes + _COMMON_NOTES + (_X86_NOTE if is_5x else "")
    return Recipe(
        family="jemalloc",
        version=version,
        upstream="https://github.com/jemalloc/jemalloc",
        license="BSD-2-Clause",
        # The same tags the MinGW recipe pins.
        source=Source(git_url="https://github.com/jemalloc/jemalloc.git",
                      git_ref=version),
        build=[
            BuildStep(_CHECK_BASH),
            _autogen(is_5x, version, commit),
            _TAIL,
            BuildStep(_CHECK_HEADERS),
            BuildStep(_props(is_5x)),
            BuildStep(_MSBUILD % sln),
            BuildStep(_TLOGS, allow_failure=True),
            BuildStep("dumpbin /dependents " + _OUT + "jemalloc.dll",
                      allow_failure=True),
            BuildStep("dir " + _OUT, allow_failure=True),
        ],
        artifacts=[Artifact(path=_OUT + "jemalloc.dll",
                            component="jemalloc.dll",
                            pdb=_OUT + "jemalloc.pdb")],
        toolchains=["msvc_x86", "msvc_x64"],
        build_flags=_FLAGS,
        notes=notes,
    )


RECIPES = {
    "jemalloc_4.5.0_msvc": _jemalloc_msvc(
        "4.5.0", "04380e79f1e2428bd0ad000bbc6e3d2dfc6b66a5",
        "jemalloc_vc2015.sln", False,
        "Last of the 4.x line: the extent machinery is in, but not the 5.x "
        "background thread, arena decay or rtree rewrite. "),
    "jemalloc_5.2.1_msvc": _jemalloc_msvc(
        "5.2.1", "ea6b3e973b477b8061e0076bb257dbd7f3faa756",
        "jemalloc_vc2017.sln", True,
        "The 5.x generation a great deal of shipped software links, before "
        "5.3 added the HPA, the SEC and psset. "),
    "jemalloc_5.3.0_msvc": _jemalloc_msvc(
        "5.3.0", "54eaed1d8b56b1aa528be3bdd1877e59c56fa90c",
        "jemalloc_vc2017.sln", True,
        "The current line as most binaries carry it, and the first with the "
        "HPA, the SEC and psset. "),
    "jemalloc_5.4.0_msvc": _jemalloc_msvc(
        "5.4.0", "7a34f18502e7b222724097cdcd499b437d189acc",
        "jemalloc_vc2022.sln", True,
        "Current release, and the only tag whose solution is upstream's own "
        "vc2022 (v143) one, kept beside 5.3.0 rather than replacing it. "),
}
