"""Re-apply the compiler-runtime filter to already-committed reports.

The glue baseline is measured, not hardcoded, which is what keeps it from
rotting with the next compiler - but it also means the baseline can improve
after a family has been built and committed. It did: the x86 probe gained
64-bit division, which pulls libgcc's ``__divdi3``, ``__moddi3``,
``__udivdi3``, ``__umoddi3``, ``__divmoddi4`` and ``__udivmoddi4`` into the
baseline. Every 32-bit artefact built before that carries whichever of those
six it links, wearing the library's family name instead of the compiler's.

They are few - one to six per artefact - but they are exactly the functions
that cause false cross-family matches, because ``__udivmoddi4`` is the same
code in every x86 binary that divides a 64-bit integer. Left alone they are
the bulk of what survives the ten-instruction floor on ``validate --deep``.

Rebuilding 37 families to remove them would cost hours of compilation and
would produce the same disassembly, because nothing about the binaries
changes - only which of their functions this repository is willing to
attribute to the project. So the committed reports are filtered in place
instead, by the same ``is_glue`` the pipeline uses.

What that costs in fidelity was measured rather than assumed. Reading a
committed report back, re-exporting it and diffing against the committed
.mcrit gives one difference: the ``timestamp`` inside each entry of
``function_labels``, which MCRIT writes when it records a label. Labels
themselves, minhashes, PicHashes, sample entries and the export config are
identical. That is the same instability a rebuild has, so a refiltered pair
is what a rebuild would have produced.

The archive is patched as stored JSON rather than re-serialised from the
parsed report, for the reason reprocess.py gives: ``SmdaReport.toDict()``
drops ``xdata_refs_from`` entries, and a correction has no business
discarding data it was not asked about.

    python scripts/build_corpus.py refilter [family ...]
    python scripts/build_corpus.py refilter --dry-run
"""

import json
import logging
import os
import shutil
import tempfile

from . import config, export, package, recipes
from .baseline import is_glue
from .reprocess import _read_archive, _write_archive, _export_path
from .smdaify import _recompute_statistics


LOGGER = logging.getLogger(__name__)


class RefilterError(RuntimeError):
    """An artefact that cannot be corrected in all of the files that hold it."""


def _filter_is_off_for():
    """Families whose recipes turn the glue filter off.

    A match in one of those is the point of the family, not leakage:
    data/libstdc++ exists to carry the C++ runtime, and SysWhispers links no
    runtime at all. Reading it from the recipes rather than listing it here
    means a recipe that changes its mind does not need this file changed too.
    """
    return {recipe.family for recipe in recipes.all_recipes().values()
            if not recipe.drop_crt_glue}


def _artifacts(families=None):
    """Yield (family, slug, entry, archive) for generated artefacts.

    Only families carrying a provenance record, which is what marks a family
    as produced by this tooling; the IDA-derived ones came from elsewhere and
    are not this contribution's to rewrite.
    """
    root = config.DATA_DIR
    off = _filter_is_off_for()
    names = families or sorted(name for name in os.listdir(root)
                               if os.path.isdir(os.path.join(root, name)))
    for family in names:
        provenance_path = os.path.join(root, family, "provenance.json")
        if not os.path.exists(provenance_path):
            LOGGER.debug("skipping %s: not generated by this tooling", family)
            continue
        if family in off:
            LOGGER.info("skipping %s: its recipe turns the glue filter off",
                        family)
            continue
        with open(provenance_path, encoding="utf-8") as handle:
            provenance = json.load(handle)
        for slug, entry in sorted(provenance.items()):
            if not entry.get("toolchain"):
                # A blob was compiled upstream; the recorded toolchain is None
                # and there is no baseline that describes it.
                continue
            archive = os.path.join(config.REPO_ROOT, entry["smda"])
            if not os.path.exists(archive):
                LOGGER.warning("%s: %s is recorded but missing", slug, archive)
                continue
            yield family, slug, entry, archive


def _glue_offsets(report, toolchain_id):
    return [offset for offset, function in report.xcfg.items()
            if is_glue(function, toolchain_id)]


def _corrected_archive(report_dict, report, offsets):
    """Apply the removal to both the parsed report and the stored dict.

    The parsed report is mutated so the statistics can be recomputed over what
    survives, exactly as the pipeline does it; the stored dict is what gets
    written back. xcfg is keyed by offset, and JSON has no integer keys, so
    the stored side is addressed by the decimal string SMDA wrote.
    """
    removed = []
    for offset in offsets:
        removed.append(report.xcfg[offset].function_name)
        del report.xcfg[offset]
        # SMDA writes xcfg keys as decimal strings; anything else means the
        # report was not written by SMDA and must not be guessed at.
        key = str(offset)
        if key not in report_dict["xcfg"]:
            raise RefilterError(
                "offset %d is in the parsed report but not at %r in the stored "
                "one, so the two do not describe the same functions" % (offset, key))
        del report_dict["xcfg"][key]
    # getFunctions() memoises, so the removal is invisible downstream without
    # this - the same trap smdaify._drop_crt_glue documents.
    report._sorted_functions = None
    _recompute_statistics(report)
    report_dict["statistics"] = report.statistics.toDict()
    report_dict.setdefault("metadata", {})["binweight"] = report.binweight
    return sorted(removed)


def _write_export(path, report):
    """Re-export ``report`` over ``path``, atomically.

    export_reports writes straight to its target, which is right for the work
    directory the pipeline gives it and wrong for a committed file: an
    interrupted write would leave a truncated .mcrit with no way back. It is
    written to a scratch directory beside the target and moved over it.
    """
    staging = tempfile.mkdtemp(dir=os.path.dirname(path) or ".",
                               prefix=".refilter-")
    try:
        fresh = os.path.join(staging, os.path.basename(path))
        export.export_reports([report], fresh)
        package.check_size(fresh)
        with open(fresh, encoding="utf-8") as handle:
            text = handle.read()
    finally:
        # package._discard is os.remove, which cannot take a directory.
        shutil.rmtree(staging, ignore_errors=True)
    package.atomic_write_text(path, text)


def refilter(families=None, dry_run=False):
    """Drop newly-recognised compiler runtime from the committed reports.

    Returns (changes, failures). Each change is (slug, [names removed]); each
    failure is a message about an artefact left exactly as it was found.

    An artefact is corrected in all three places that describe it - the .7z,
    the .mcrit and the provenance record - or in none of them. Reading and
    filtering happen first, so an artefact that cannot be corrected costs only
    itself and the rest of the corpus is still walked.

    ``dry_run`` reports what would go without writing anything, which is how
    to see the scale of a baseline change before spending the corpus on it.
    """
    changes = []
    failures = []
    from smda.common.SmdaReport import SmdaReport

    for family, slug, entry, archive in _artifacts(families):
        toolchain_id = entry["toolchain"]
        try:
            member, report_dict = _read_archive(archive)
            report = SmdaReport.fromDict(report_dict)
            offsets = _glue_offsets(report, toolchain_id)
        except (OSError, RuntimeError, ValueError, KeyError) as error:
            failures.append("%s: not read: %s" % (slug, error))
            continue
        if not offsets:
            continue

        export_path = _export_path(archive, slug)
        if not os.path.exists(export_path):
            failures.append("%s: no .mcrit at %s, so the pair cannot be kept "
                            "in step; archive left alone" % (slug, export_path))
            continue

        try:
            removed = _corrected_archive(report_dict, report, offsets)
        except (RefilterError, KeyError) as error:
            failures.append("%s: %s" % (slug, error))
            continue

        if dry_run:
            LOGGER.info("%s: would drop %d (%s)", slug, len(removed),
                        ", ".join(removed))
            changes.append((slug, removed))
            continue

        # The export is rebuilt from the filtered report before the archive is
        # touched: if MCRIT cannot index it, nothing has been written yet and
        # the committed pair still agrees with itself.
        try:
            _write_export(export_path, report)
        except (OSError, RuntimeError, ValueError) as error:
            failures.append("%s: export not rewritten, archive untouched: %s"
                            % (slug, error))
            continue
        try:
            _write_archive(archive, member, report_dict)
        except (OSError, RuntimeError) as error:
            # The export is already the filtered one. Two files cannot be
            # written at once, so this window cannot be closed - it is
            # reported loudly rather than logged and forgotten.
            failures.append("%s: %s was rewritten but %s could not be: %s"
                            % (slug, export_path, archive, error))
            continue

        # Provenance last, because it is the cheapest to redo by hand and the
        # only one of the three a reader would notice was missing.
        recorded = sorted(set(entry.get("removed_runtime_functions") or ())
                          | set(removed))
        try:
            package.write_provenance(family, {slug: dict(
                entry,
                num_functions=report.num_functions,
                removed_runtime_functions=recorded)})
        except OSError as error:
            failures.append("%s: data rewritten but provenance was not: %s"
                            % (slug, error))
            continue

        LOGGER.info("%s: dropped %d (%s)", slug, len(removed),
                    ", ".join(removed))
        changes.append((slug, removed))
    return changes, failures
